# Generated by Django 4.1 on 2022-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabDois', '0004_alter_aluno_periodo_ingresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota - Web Avançado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo_ingresso',
            field=models.CharField(max_length=50, verbose_name='Período de Ingresso'),
        ),
    ]
